"""Semantic error taxonomy used by the verifier and repair routines."""

from __future__ import annotations

from enum import Enum


class SemanticTag(str, Enum):
    CONTRADICTION = "CONTRADICTION"
    UNSUPPORTED = "UNSUPPORTED"
    VARIABLE_DRIFT = "VARIABLE_DRIFT"
    UNIT_MISMATCH = "UNIT_MISMATCH"
    DEFINITION_DRIFT = "DEFINITION_DRIFT"
    ILLEGAL_INFERENCE = "ILLEGAL_INFERENCE"
    CIRCULARITY = "CIRCULARITY"
    MISQUOTE = "MISQUOTE"
    UNCITED_CLAIM = "UNCITED_CLAIM"
    QUOTE_OOC = "QUOTE_OOC"
    OVERCLAIMED_CAUSALITY = "OVERCLAIMED_CAUSALITY"
    IS_OUGHT_SLIP = "IS_OUGHT_SLIP"
    RHETORICAL_EXCESS = "RHETORICAL_EXCESS"
    ENTAILED = "ENTAILED"
    SUPPORTED = "SUPPORTED"


__all__ = ["SemanticTag"]
